# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc0e8293fd5acedc294792e98ae69ea2ede0bdd722842994fc86422f3312e8b2eccccf2522a891f314abda123dd8600f601c89b46d2a3ff16b334481a8c9341

test:
  secret_key_base: f9cbe66351d16898578615c5c096f835a4207d0c5da117788328b9e7ea90517194dee832df37d4e4ebfc8005aa1520ea8febdfcf785ab986046c3487e0ddf3a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
